modLoader="javafml"
loaderVersion="[43,)"
license="All Rights Reserved"

[[mods]]
modId="capybara"
version="1.0"
displayName="Capybara Mod"
#updateJSONURL="https://change.me.example.invalid/updates.json"
#displayURL="https://change.me.to.your.mods.homepage.example.invalid/"
logoFile="capylogo.jpg"
credits="GITIPI"
authors="GITIPI"
description='''
Adds Capybara
'''